; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_f405]
platform = ststm32
board = adafruit_feather_f405
framework = arduino
lib_deps = 
	adafruit/Adafruit BNO08x@^1.2.5
	adafruit/Adafruit LPS2X@^2.0.6
	sparkfun/SparkFun u-blox GNSS Arduino Library@^2.2.28
	stm32duino/STM32duino STM32SD@^1.4.0
	https://github.com/adafruit/RadioHead.git
upload_protocol = dfu
monitor_port = COM5
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC

